---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-341 A} | Spring 2025}
  \fancyhead[RO,R]{\textbf{Worksheet 8} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** Worksheets are graded mostly on completion, and partially on correctness. Please write complete solutions showing explanations and key steps to the following problems, unless it says otherwise.
\noindent\rule{\textwidth}{1pt}

## Testing for Linear Independence

This worksheet has a supplementary Jupyter Notebook (Python) in Posit Cloud. Please log-in into this course's Posit Cloud Workspace and navigate to the appropriate environment.

### 1. Spanning Subsets

A set of vectors $\{\vec{v}_1, \vec{v}_2, \cdots \vec{v}_k\}$ in a vector space $V$ is said to be:

* *Spanning* if for all $\vec{v} \in V$, there exist $c_1, c_2, \cdots c_k \in \mathbb{R}$ so that $\displaystyle \vec{v} = c_1 \vec{v}_1 + c_2 \vec{v}_2 + \cdots + c_k \vec{v}_k$ or $\displaystyle \text{Span}\left(\{\vec{v}_1, \vec{v}_2, \cdots \vec{v}_k\}\right) = \vec{v}$.

* *Linearly independent* if and only if the solution to $\displaystyle c_1 \vec{v}_1 + c_2 \vec{v}_2 + \cdots + c_k \vec{v}_k = \vec{0}$ is $\displaystyle c_1 = c_2, \cdots, c_k = 0$.

For each set of vectors, determine whether they are linearly independent or dependent, and determine if the set spans the given vector space.

a. $\displaystyle \left\{ \begin{bmatrix} 1 \\ 2 \end{bmatrix}, \begin{bmatrix} 3 \\ 5 \end{bmatrix} \right\} \text{ in } \mathbb{R}^2$
\vfill
b. $\displaystyle \left\{ \begin{bmatrix} 1 \\ 1 \\ 8 \end{bmatrix}, \begin{bmatrix} -3 \\ 4 \\ 2 \end{bmatrix}, \begin{bmatrix} 7 \\ -1 \\ 3 \end{bmatrix} \right\} \text{ in } \mathbb{R}^3$
\vfill

\newpage

### 2. A Questionable Basis

A set that is both spanning and linearly independent forms a *basis* of the vector space $V$: $\text{Span}\left(\{\vec{v}_1, \vec{v}_2, \cdots \vec{v}_k\}\right) \in V$ and $\{\vec{v}_1, \vec{v}_2, \cdots \vec{v}_k\}$ is linearly independent.

Consider the set of vectors $$S = \left\{ \begin{bmatrix} 1 \\ 1 \\ 0 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}, \begin{bmatrix} 2 \\ 1 \\ -1 \end{bmatrix} \right\}.$$

a. Show that $S$ is linearly dependent.
\vfill

b. Explain why $S$ is not a basis for $\mathbb{R}^3$.
\vfill

c. Change one of the vectors in $S$ to form a basis for $\mathbb{R}^3$. Explain your reasoning.
\vfill

d. Describe the differences of the set vectors in $S$ and the new set of vectors in Part (c) on how they would look like in $\mathbb{R}^3$.
\vfill

<!-- \newpage

## **References**

::: {#refs}
:::

<br> -->
