---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-341 A} | Spring 2025}
  \fancyhead[RO,R]{\textbf{Worksheet 4} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** Worksheets are graded mostly on completion, and partially on correctness. Please write complete solutions showing explanations and key steps to the following problems, unless it says otherwise.
\noindent\rule{\textwidth}{1pt}

## Gauss-Jordan Elimination

### 1. Gauss-Jordan's Method

*Gauss–Jordan elimination* is the extension of Gaussian elimination that takes you one step further: instead of stopping at *row echelon form* (REF), you keep eliminating until you reach *reduced row echelon form* (RREF). This method have three rules:

* **(1) Start from row echelon form.** Each pivot column has zeros below the pivot.
* **(2) Normalize each pivot.** Scale each pivot row so that the pivot entry is exactly $1$.
* **(3) Row reduce.** Use each pivot to eliminate all the entries above it using Gauss's method.

By the end, each pivot column has a $1$ with zeros everywhere else. This guarantees that the augmented matrix is in RREF, which makes it straightforward to read off the solutions to the system where every variable is either directly solved or clearly expressed in terms of free variables.

Use the Gauss-Jordan elimination to solve the system of equations:
$$
\begin{aligned}
x + 2y + z & = 3 \\
2x + 4y + 2z & = 6 \\
-x - 2y + z & = 1
\end{aligned}
$$
Show each step clearly, including the operations you apply. If the result has infinite solutions, write it in parametric form.
\vfill

\newpage

*This page is intentionally left blank.*

<!-- \newpage

## **References**

::: {#refs}
:::

<br> -->
