---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-341 A} | Spring 2025}
  \fancyhead[RO,R]{\textbf{Worksheet 3} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
  \usepackage{enumitem}
  \usepackage{tasks}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** Worksheets are graded mostly on completion, and partially on correctness. Please write complete solutions showing explanations and key steps to the following problems, unless it says otherwise.
\noindent\rule{\textwidth}{1pt}

## Row Echelon Form

### 1. Solution Types and Echelon Forms

Consider the system of $m$ linear equations with $n$ variables $x_1$, $x_2$, $\cdots$, $x_n$ in general form:
$$
\begin{aligned}
a_{11} x_1 + a_{12} x_2 + \cdots + a_{1n} x_n & = b_1 \\
a_{21} x_1 + a_{22} x_2 + \cdots + a_{2n} x_n & = b_2 \\
\vdots & \\
a_{m1} x_1 + a_{m2} x_2 + \cdots + a_{mn} x_n & = b_m \\
\end{aligned} \xrightarrow{\text{augmented matrix}}
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} & | & b_1 \\
a_{21} & a_{22} & \cdots & a_{2n} & | & b_2 \\
\vdots & \vdots & \ddots & \vdots &   & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn} & | & b_m \\
\end{bmatrix}
$$
where $a_{ij}$ and $b_i$ are constants for $i \in \{1,2,\cdots,m\}$ and $j \in \{1,2,\cdots,n\}$.

The goal of Gussian elimination is to reach *row echelon form* (REF) of the augmented matrix, a simplified version of the matrix where each nonzero row starts with a leading entry (called a *pivot*) to the right of the one above it, and all rows of zeros are at the bottom.

For each of the following augmented matrices already in REF:

* Identify the number of equations $m$ and variables $n$.
* Classify if the system is overdetermined, underdetermined, or neither.
* Determine if the system has a unique solution, infinite solutions, or no solution.
* If the the system have infinite solutions, list the free variables.

\

\begin{tasks}[after-item-skip=2in](2)
  \task $\displaystyle \begin{bmatrix} 1 & -3 & 2 & -1 & | & 2 \\ 0 & 0 & 0 & 1 & | & 1 \end{bmatrix}$
  \task $\displaystyle \begin{bmatrix} 1 & -3 & -1 & | & 0 \\ 0 & 1 & 1 & | & -1 \\ 0 & 0 & 1 & | & 0 \\ 0 & 0 & 0 & | & 0 \\ 0 & 0 & 0 & | & 0 \end{bmatrix}$
\end{tasks}

\newpage

### 2. More Examples

For each of the following augmented matrices already in *row echelon form*:

* Identify the number of equations $m$ and variables $n$.
* Classify if the system is overdetermined, underdetermined, or neither.
* Determine if the system has a unique solution, infinite solutions, or no solution.
* If the the system have infinite solutions, list the free variables.

\

\begin{tasks}[after-item-skip=1.5in](2)
  \task $\displaystyle \begin{bmatrix} 1 & 2 & | & 5 \\ 0 & 1 & | & 3 \end{bmatrix}$
  \task $\displaystyle \begin{bmatrix} 1 & 2 & | & 3 \end{bmatrix}$
  \task $\displaystyle \begin{bmatrix} 1 & 0 & 2 & | & 4 \\ 0 & 0 & 1 & | & 3 \\ 0 & 0 & 0 & | & 0 \end{bmatrix}$
  \task $\displaystyle \begin{bmatrix} 1 & -1 & | & 3 \\ 0 & 0 & | & 1 \\ 0 & 0 & | & 0 \end{bmatrix}$
  \task $\displaystyle \begin{bmatrix} 1 & 4 & 0 & | & 2 \\ 0 & 1 & -5 & | & -1 \\ 0 & 0 & 1 & | & -1 \end{bmatrix}$
  \task $\displaystyle \begin{bmatrix} 1 & 0 & 3 & | & 2 \\ 0 & 1 & -5 & | & 1 \end{bmatrix}$
  \task $\displaystyle \begin{bmatrix} 0 & 1 & 3 & | & 1 \\ 0 & 0 & 1 & | & 2 \end{bmatrix}$
  \task $\displaystyle \begin{bmatrix} 1 & 3 & 5 & 2 & | & 1 \\ 0 & 0 & 1 & 2 & | & 3 \\ 0 & 0 & 0 & 0 & | & 0 \end{bmatrix}$
\end{tasks}

<!-- \newpage

## **References**

::: {#refs}
:::

<br> -->
